library(quantmod)
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(DT)
library(tidyverse)
library(lubridate)

airline_list <- c('American', 'Continental', 'Delta')
data_options <- c('Despesas', 'Receita', 'Passageiros')